### ISSUE TITLE
Strange issue with registerInvocation(andReturn)

### ISSUE THREAD

**Issue by jblejder** [lvsti/MockSix#3]
On my Bitrise Ci i had series of successful builds. 
Then one of my test failed for class I did not change. 
`Fatal error: MockSix: Incompatible block of type '(Array<Optional<Any>>) throws -> Array<Colleague>' registered for function 'logIn()' requiring block type '([Any?]) -> PrimitiveSequence<SingleTrait, ()>': file /Users/vagrant/git/Pods/MockSix/Sources/MockSix/MockSixInternal.swift, line 160
`
I did register invocations like this:
`func logIn() -> Single<Void> {
    return registerInvocation(for: .logIn, andReturn: Single.just(()))
}`
I ran two more builds just in case and they passed.

**Comment by lvsti** [comment]
Hi, are you calling `resetMockSix()` at the beginning of each test run?

**Comment by jblejder** [comment]
No I did not. That might be a case thanks.

**Comment by lvsti** [comment]
Did it solve your problem? Can I close this issue?

**Comment by jblejder** [comment]
Yes it fixed problem. Thanks.
But I did not find it in documentation therefore maybe worth adding?

**Comment by lvsti** [comment]
Yeah, good idea, will do it soon.

**Comment by lvsti** [comment]
done!
